use_frameworks!

target 'RxApolloClient_Example' do
  pod 'RxApolloClient', :path => '../'
  pod 'RxCocoa'
  pod 'RxOptional'
  
  target 'RxApolloClient_Tests' do
    inherit! :search_paths
    
  end
end
